// Next head
import Head from "next/head";
// Components
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import About from "../components/About";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import SocialMedia from "../components/SocialMedia";
// React
import { useState } from "react";

export default function Home() {
  // const [menu, setMenu] = useState(false);
  return (
    <div>
      <Head>
        <title>Hrutvik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Favicon.png" />
      </Head>
      {/* //TODO: Untouchable */}
      {/* <div
        className={`absolute top-0 -bottom-[600%] w-full  bg-[#0a192f21] backdrop-blur-md z-40 ${
          menu ? "visible" : "hidden"
        }`}
      ></div> */}
      <Navbar/>
      <SocialMedia />
      <Hero />
      <About />
      <Projects />
      <Contact />
    </div>
  );
}
