import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Hero from "../components/Hero";
import About from "../components/About";
import Projects from "../components/Projects";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hrutvik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Favicon.png" />
      </Head>
      <Navbar />
      <Hero />
      <About />
      <Projects />
      <Contact/>
    </div>
  );
}
